enum TodoActionType {
    GET_TODOS_REQUEST = 'GET_TODOS_REQUEST',
    GET_TODOS_SUCCEEDED= 'GET_TODOS_SUCCEEDED',
    GET_TODOS_FAILED = 'GET_TODOS_FAILED',

    ADD_TODO_REQUEST = 'ADD_TODO_REQUEST',
    ADD_TODO_SUCCEEDED= 'ADD_TODO_SUCCEEDED',
    ADD_TODOS_FAILED = 'ADD_TODOS_FAILED',

    TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST',
    TOGGLE_TODO_SUCCEEDED= 'TOGGLE_TODO_SUCCEEDED',
    TOGGLE_TODOS_FAILED = 'TOGGLE_TODOS_FAILED',

    DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST',
    DELETE_TODO_SUCCEEDED= 'DELETE_TODO_SUCCEEDED',
    DELETE_TODOS_FAILED = 'DELETE_TODOS_FAILED',
}

export default TodoActionType;
